// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YPM.Veri.Kaynak;

namespace YPM.Veri.Migrations
{
    [DbContext(typeof(YpmSebil))]
    [Migration("20180317073614_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kisi.Ortak.KisiGercek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<string>("EPosta");

                    b.Property<string>("Sifre");

                    b.Property<string>("Soyad");

                    b.HasKey("Id");

                    b.ToTable("KisiTbl");
                });

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kurulum.Ortak.KurulumGercek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<bool>("Sonuc");

                    b.Property<string>("Tip");

                    b.HasKey("Id");

                    b.ToTable("KurulumTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
