// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YPM.Veri.Kaynak;

namespace YPM.Veri.Migrations
{
    [DbContext(typeof(YpmSebil))]
    [Migration("20180405134739_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Mulk")
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kisi.Ortak.KisiGercek", b =>
                {
                    b.Property<int>("KisiId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad")
                        .HasMaxLength(400);

                    b.Property<string>("EPosta")
                        .HasMaxLength(150);

                    b.Property<string>("EpostaKontrol")
                        .HasMaxLength(20);

                    b.Property<bool>("EpostaOnayliMi");

                    b.Property<DateTime>("KayitTarihi");

                    b.Property<string>("Sifre")
                        .HasMaxLength(400);

                    b.Property<string>("Soyad")
                        .HasMaxLength(400);

                    b.HasKey("KisiId");

                    b.ToTable("Kisi","MulkKisi");
                });

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kurulum.Ortak.KurulumGercek", b =>
                {
                    b.Property<int>("KurulumId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad")
                        .HasMaxLength(200);

                    b.Property<bool>("Sonuc");

                    b.Property<string>("Tip")
                        .HasMaxLength(200);

                    b.HasKey("KurulumId");

                    b.ToTable("Kurulum","MulkKurulum");
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Kisi.Ortak.LokasyonGercek", b =>
                {
                    b.Property<int>("LokasyonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IpAdr")
                        .HasMaxLength(200);

                    b.Property<DateTime>("KayitTarihi");

                    b.Property<int>("KisiId");

                    b.Property<string>("MacAdr")
                        .HasMaxLength(200);

                    b.HasKey("LokasyonId");

                    b.HasIndex("KisiId");

                    b.ToTable("Lokasyon","MulkKisi");
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Urun.Kategori.UrunKategoriGercek", b =>
                {
                    b.Property<int>("UrunKategoriId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aciklama")
                        .HasMaxLength(400);

                    b.Property<string>("Ad")
                        .HasMaxLength(250);

                    b.Property<bool>("AktifMi");

                    b.Property<string>("AnahtarKelime")
                        .HasMaxLength(400);

                    b.Property<int>("BabaId");

                    b.Property<string>("SayfaBaslik")
                        .HasMaxLength(250);

                    b.Property<string>("Tanim")
                        .HasMaxLength(400);

                    b.HasKey("UrunKategoriId");

                    b.ToTable("UrunKategori","MulkUrun");
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Urun.Kategori.UrunKategoriNitelikGercek", b =>
                {
                    b.Property<int>("UrunKategoriNitelikId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UrunKategoriId");

                    b.Property<int>("UrunNitelikId");

                    b.HasKey("UrunKategoriNitelikId", "UrunKategoriId", "UrunNitelikId");

                    b.HasIndex("UrunKategoriId");

                    b.HasIndex("UrunNitelikId");

                    b.ToTable("UrunKategoriNitelik","MulkUrun");
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Urun.Kategori.UrunNitelikGercek", b =>
                {
                    b.Property<int>("UrunNitelikId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad")
                        .HasMaxLength(250);

                    b.HasKey("UrunNitelikId");

                    b.ToTable("UrunNitelik","MulkUrun");
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Kisi.Ortak.LokasyonGercek", b =>
                {
                    b.HasOne("GercekVarlik.Mulk.Varlik.Kisi.Ortak.KisiGercek", "Kisi")
                        .WithMany("Lokasyonlar")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Urun.Kategori.UrunKategoriNitelikGercek", b =>
                {
                    b.HasOne("YPM.GercekVarlik.Mulk.Varlik.Urun.Kategori.UrunKategoriGercek", "Kategori")
                        .WithMany("KategoriNitelik")
                        .HasForeignKey("UrunKategoriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YPM.GercekVarlik.Mulk.Varlik.Urun.Kategori.UrunNitelikGercek", "Nitelik")
                        .WithMany("KategoriNitelik")
                        .HasForeignKey("UrunNitelikId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
