// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YPM.Veri.Kaynak;

namespace YPM.Veri.Migrations
{
    [DbContext(typeof(YpmSebil))]
    partial class YpmSebilModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Mulk")
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kisi.Ortak.KisiGercek", b =>
                {
                    b.Property<int>("KisiId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad")
                        .HasMaxLength(400);

                    b.Property<string>("EPosta")
                        .HasMaxLength(150);

                    b.Property<string>("EpostaKontrol")
                        .HasMaxLength(20);

                    b.Property<bool>("EpostaOnayliMi");

                    b.Property<DateTime>("KayitTarihi");

                    b.Property<string>("Sifre")
                        .HasMaxLength(400);

                    b.Property<string>("Soyad")
                        .HasMaxLength(400);

                    b.HasKey("KisiId");

                    b.ToTable("Kisi","MulkKisi");
                });

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kurulum.Ortak.KurulumGercek", b =>
                {
                    b.Property<int>("KurulumId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad")
                        .HasMaxLength(200);

                    b.Property<bool>("Sonuc");

                    b.Property<string>("Tip")
                        .HasMaxLength(200);

                    b.HasKey("KurulumId");

                    b.ToTable("Kurulum","MulkKurulum");
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Kisi.Ortak.LokasyonGercek", b =>
                {
                    b.Property<int>("LokasyonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IpAdr")
                        .HasMaxLength(200);

                    b.Property<DateTime>("KayitTarihi");

                    b.Property<int>("KisiId");

                    b.Property<string>("MacAdr")
                        .HasMaxLength(200);

                    b.HasKey("LokasyonId");

                    b.HasIndex("KisiId");

                    b.ToTable("Lokasyon","MulkKisi");
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Urun.Kategori.UrunKategoriGercek", b =>
                {
                    b.Property<int>("UrunKategoriId");

                    b.Property<int>("UrunUstKategoriId");

                    b.Property<string>("Ad")
                        .HasMaxLength(250);

                    b.Property<string>("LinkYol")
                        .HasMaxLength(250);

                    b.Property<string>("ResimYol")
                        .HasMaxLength(250);

                    b.HasKey("UrunKategoriId", "UrunUstKategoriId");

                    b.ToTable("Kategori","MulkUrun");
                });

            modelBuilder.Entity("YPM.GercekVarlik.Mulk.Varlik.Kisi.Ortak.LokasyonGercek", b =>
                {
                    b.HasOne("GercekVarlik.Mulk.Varlik.Kisi.Ortak.KisiGercek", "Kisi")
                        .WithMany("Lokasyonlar")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
