// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YPM.Veri.Kaynak;

namespace YPM.Veri.Migrations
{
    [DbContext(typeof(YpmSebil))]
    partial class YpmSebilModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Mulk")
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kisi.Ortak.KisiGercek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad")
                        .HasMaxLength(400);

                    b.Property<string>("EPosta")
                        .HasMaxLength(150);

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("select getdate()");

                    b.Property<string>("Sifre")
                        .HasMaxLength(400);

                    b.Property<string>("Soyad")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("Kisi","MulkKisi");
                });

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kurulum.Ortak.KurulumGercek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<bool>("Sonuc");

                    b.Property<string>("Tip");

                    b.HasKey("Id");

                    b.ToTable("KurulumTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
